books/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'books'

urlpatterns = [
	path('', views.landing, name='landing'),
	path('index/', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('reviews/', views.reviews, name='reviews'),
	path('contact/', views.contact, name='contact'),
	path('about/', views.about, name='about'),
    path('pricing/', views.pricing, name='pricing'),
    path('contact/', views.contact, name='contact'),
    path('faqs/', views.faqs, name='faqs'),
    path('privacy/', views.privacy, name='privacy'),
   	path('login/', auth_views.LoginView.as_view(template_name='books/login.html', authentication_form=LoginForm), name='login'),
 	path('logout/', auth_views.LogoutView.as_view(next_page=''), name='logout'),
]

conversation/urls.py
from django.urls import path

from . import views

# coversation/urls.py
# Set the namespace for the app
app_name = 'conversation'

# Define the urlpatterns for the app
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:file_pk>/', views.new_conversation, name='new'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

file/urls.py
from django.urls import path

from . import views

app_name = 'file'

urlpatterns = [
    path('', views.files, name='files'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:file_id>/download/', views.download, name='download'),  # Corrected URL pattern
    path('<int:file_id>/payment/', views.payment, name='payment'),
    path('<int:file_id>/process_payment/', views.process_payment, name='process_payment'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('books.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('file/', include('file.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
	title = models.CharField(max_length=100)
	author = models.CharField(max_length=100)
	genre = models.CharField(max_length=50)
	publication_year = models.PositiveIntegerField()
	isbn = models.CharField(max_length=13)
	language = models.CharField(max_length=50)
	description = models.TextField()
	cover_image = models.ImageField(upload_to='book_covers/')
	available = models.BooleanField(default=True)
	rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
	num_ratings = models.IntegerField(default=0)
	tags = models.CharField(max_length=100, blank=True)

	def __str__(self):
		return self.title 


class BorrowHistory(models.Model):
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	borrower = models.ForeignKey(User, on_delete=models.CASCADE)
	borrow_date = models.DateField(auto_now_add=True)
	return_date = models.DateField(null=True, blank=True)

	def __str__(self):
		return f"{self.book.title} - {self.borrower.username}"

books/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
	"""
    A form for user login.

    Inherits from the Django AuthenticationForm class.
    Adds custom widget attributes for 'username' and 'password' fields.
    """
	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))


class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = {'username', 'email', 'password1', 'password2'}

	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder': 'Your email address',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Repeat password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

books/views.py
from django.shortcuts import render, redirect

from file.models import Category, File

from .forms import SignupForm

from django.contrib.auth import logout




def index(request):
    # Fetch all featured books
    files = File.objects.all()

    # Fetch files by category for display
    files_by_category = {}
    categories = Category.objects.all()
    for category in categories:
        files_by_category[category] = File.objects.filter(category=category)

    context = {
        'files': files,
        'files_by_category': files_by_category,
    }

    return render(request, 'books/index.html', context)


def landing(request):
    """
    This function handles the landing page.
    
    :param request: The HTTP request object.
    :return: The rendered landing page.
    """
    # Retrieve all categories
    categories = Category.objects.all()

    # Create a dictionary to store files grouped by category
    files_by_category = {}

    # Iterate over each category
    for category in categories:
        # Retrieve files for the current category
        files = File.objects.filter(category=category)
        # Store files in the dictionary with category as key
        files_by_category[category] = files


    # Pass grouped data to template
    return render(request, 'books/landing.html', {'files_by_category': files_by_category})



def contact(request):
    """
     This function handles the review page.
    
    :param request: The HTTP request object.
    :return: The rendered review page.
    """
    return render(request, 'books/contact.html')


def faqs(request):
    """
     This function handles the FAQS page.
    
    :param request: The HTTP request object.
    :return: The rendered review page.
    """
    return render(request, 'books/faqs.html')


def privacy(request):
    """
     This function handles the Pricacy & Policy page.
    
    :param request: The HTTP request object.
    :return: The rendered review page.
    """
    return render(request, 'books/privacy.html')


def about(request):
    """
    This function handles the about page.
    
    :param request: The HTTP request object.
    :return: The rendered about page.
    """
    return render(request, 'books/about.html')



def pricing(request):
    """
    This function handles the pricing page.
    
    :param request: The HTTP request object.
    :return: The rendered pricing page.
    """
    return render(request, 'books/pricing.html')



def reviews(request):
    """
     This function handles the review page.
    
    :param request: The HTTP request object.
    :return: The rendered review page.
    """
    return render(request, 'books/reviews.html')



def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    else:
        form = SignupForm()

    return render(request, 'books/signup.html', {
        'form': form
    })



def logout(request):
    """
    This function handles the logout page.
    
    :param request: The HTTP request object.
    :return: The rendered logout page.
    """
    return render(request, 'books/logout.html')

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}{% endblock %}| Digi_Library</title>
		<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
		<style>
	        html {
	            scroll-behavior: smooth;
	        }
	    </style>
	</head>

	<body style="background-color: #ffffff; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5; padding: 2rem; color: #333; margin: 0; min-height: 100vh; display: flex; flex-direction: column; ">
		<nav style="position: fixed; top: 0; left: 0; width: 100%; padding: 1.5rem 1.5rem; display: flex; justify-content: space-between; align-items: center; border-bottom: 5px solid #FD6C01; background-color: white; z-index: 1000;">
		    <a href="/" class="text-xl font-semibold" style="text-decoration: none; color: gray; font-family: Arial, sans-serif; font-size: 2.25rem; font-weight: 600;">📚 DIGI-LIBRARY <span style="font-size: 1.5rem; vertical-align: middle;">&amp;</span> 🖥️</a>

			<div class="space-x-6">
				{% block extra_css %}

					<style>
					  /* Dropdown button */
					  .dropbtn {
					    background-color: #4CAF50;
					    color: white;
					    padding: 12px;
					    font-size: 20px;
					    border: 10px;
					    cursor: pointer;
					    width: 120px;
					  }

					  /* Dropdown button on hover & focus */
					  .dropbtn:hover, .dropbtn:focus {
					    background-color: #3e8e41;
					  }

					  /* Dropdown container (hidden by default) */
					  .dropdown {
					    position: relative;
					    display: inline-block;
					    border-radius: 30px;
					  }

					  /* Dropdown content */
					  .dropdown-content {
					    display: none;
					    position: absolute;
					    background-color: #f9f9f9;
					    min-width: 160px;
					    z-index: 1;
					  }

					  /* Links inside the dropdown */
					  .dropdown-content a {
					    color: black;
					    padding: 12px 16px;
					    text-decoration: none;
					    display: block;
					  }

					  /* Change color of dropdown links on hover */
					  .dropdown-content a:hover {
					    background-color: #f1f1f1;
					  }

					  /* Show the dropdown menu on hover */
					  .dropdown:hover .dropdown-content {
					    display: block;
					  }

					  /* Position the dropdown content */
					  .dropdown-content {
					    right: 0; /* Adjust as needed */
					    top: 100%; /* Position below the button */
					  }
					</style>
				{% endblock %}

				<div class="dropdown">
					  <button style="padding: 0.75rem 2.5rem; font-family: Arial, sans-serif; font-size: 1.125rem; font-weight: 600; background-color: #848c94; color: #fff; border-radius: 0.375rem; transition: background-color 0.2s ease-in-out; background-color: #219ebc; transition-delay: 5s;">Menu
					  </button>
					  <div class="dropdown-content">
						    <a href="{% url 'file:new' %}" style="font-size: 1.125rem; font-family: Arial, sans-serif; font-weight: 600; color: black; text-decoration: none; text-decoration-color: gray; text-decoration-thickness: 0.1em; text-underline-offset: 2px; transition: text-decoration-color 0.2s ease-in-out;" class="hover:text-gray-500">New Book</a>
						    <a href="{% url 'file:files' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
						    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
						    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>
					  </div>
				</div>

				{% if user.is_authenticated %}
				    <a href="{% url 'books:logout' %}" class="btn" style="font-family: Arial, sans-serif; font-weight: 600; padding: 15px 30px; border-radius: 5px; background-color: orangered; color: white; text-decoration: none;">Logout</a>
				{% else %}
				    <a href="{% url 'books:login' %}" class="btn" style="font-family: Arial, sans-serif; font-weight: 600; padding: 15px 30px; border-radius: 5px; background-color: orangered; color: white; text-decoration: none;">LogIn</a>

				    <a href="{% url 'books:signup' %}" style="background-color: transparent; padding: 0.5rem 1.5rem; border: 1px solid #4d94ff; border-radius: 0.375rem; font-weight: 600; font-size: 1rem; color: #4d94ff; transition: all 0.3s ease-in-out; text-decoration: none; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">Sign Up</a>
				{% endif %}
				
    			
			</div> 
		</nav>


		<div class="container mx-auto py-8">
			{% block content %}
			{% endblock %}
		</div>







		<!--Footer section-->

		<footer class="bg-blue-500 text-white py-4 mt-8" style="background-color: teal;">
			<div class="container mx-auto">
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
					<div>
						<h3 class="text-lg font-semibold mb-2">Quick Links</h3>
						<ul>
							<li><a href="/">Home</a></li
							<li><a href="{% url 'books:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
							<li><a href="{% url 'books:reviews' %}" class="text-lg text-teal-500 hover:text-teal-700">Testimonial</a></li>
						</ul>
					</div>

					<div>
						<h3 class="text-lg font-semibold mb-2">Information</h3>
						<ul>
							<li><a href="{% url 'books:about' %}">About Us</a></li>
							<li><a href="{% url 'books:faqs' %}">FAQs</a></li>
							<li><a href="{% url 'books:privacy' %}">Privacy Policy</a></li>
							<li><a href="#">Terms of Service</a></li>
						</ul>
					</div>

					<div>
						<h3 class="text-lg font-semibold mb-2">Connect</h3>
						<ul>
							<li><a href="library:info@libsoma.com">Email Us</a></li>
							<li><a href="tel:+2541234567">Calls Us</a></li>

							<li>
								<a href="#" target="_blank" rel="noopener noreferrer">Facebook</a>
								<a href="#" target="_blank" rel="noopener noreferrer">Twitter</a>
								<a href="#" target="_blank" rel="noopener noreferrer">Instagram</a>
							</li>
						</ul>
					</div>
					<div>
						<h3 class="text-lg font-semibold mb-2">Newsletter</h3>
						<p>Subscribe to our newsletter for updates and promotions</p>
					</div>
				</div>
				<hr class="mt-4 border-gray-400">
				<p>&copy; 2024 Library Book Collection</p>
			</div>
		</footer>
		<!--End Footer-->

	</body>
</html>

books/templates/books/faqs.html
{% extends 'books/base.html' %}

{% block title %}FAQS{% endblock %}

{% block content %}
	<style>
        /* Smooth scrolling behavior */
        html {
            scroll-behavior: smooth;
        }
        /* FAQ container styles */
        .faq-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        /* FAQ item styles */
        .faq-item {
            margin-bottom: 20px;
        }
        /* FAQ question styles */
        .faq-question {
            font-weight: bold;
            cursor: pointer;
        }
        /* FAQ answer styles */
        .faq-answer {
            display: none;
        }
    </style>

	<body style="font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5; background-color: #f5f5f5; margin: 0; padding: 0;">
		<div class="faq-container" style="max-width: 800px; margin: 0 auto; padding: 20px; background-color: #fff;">
		    <h1 style="font-size: 2rem; margin-top: 30px; margin-bottom: 20px;">Frequently Asked Questions</h1>

		    <div class="faq-item" style="margin-bottom: 20px;">
			    <div class="faq-question" onclick="toggleFAQ(this)" style="font-weight: bold; cursor: pointer; background-color: teal; color: #fff; padding: 10px 20px; border-radius: 5px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); transition: background-color 0.3s ease;">
			        How can I create an account?
			    </div>
		        <div class="faq-answer" style="display: none;">
		            <p>To create an account, simply click on the "Sign Up" button on the top navigation bar. Fill in the required information and follow the prompts to complete the registration process.</p>
		        </div>
		    </div>

		    <div class="faq-item" style="margin-bottom: 20px;">
			    <div class="faq-question" onclick="toggleFAQ(this)" style="font-weight: bold; cursor: pointer; background-color: teal; color: #fff; padding: 10px 20px; border-radius: 5px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); transition: background-color 0.3s ease;">
			        How do I search for books?
			    </div>
		        <div class="faq-answer" style="display: none;">
		            <p>You can search for books by clicking the Browse Button located at the top of the page in the Dropdown Menu Button. You can also browse through different categories to discover books.</p>
		        </div>
		    </div>


		    <div class="faq-item" style="margin-bottom: 20px;">
			    <div class="faq-question" onclick="toggleFAQ(this)" style="font-weight: bold; cursor: pointer; background-color: teal; color: #fff; padding: 10px 20px; border-radius: 5px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); transition: background-color 0.3s ease;">
			        Can I download books for offline reading
			    </div>
		        <div class="faq-answer" style="display: none;">
		            <p>Yes, if the book is available for download. You can check the book details to see if it's available for download and follow the instructions provided to download the book.</p>
		        </div>
		    </div>

		    <!-- Add more FAQ items as needed -->

		</div>
	</body>

	<script>
	    // Function to toggle FAQ answer visibility
	    function toggleFAQ(element) {
	        var answer = element.nextElementSibling;
	        if (answer.style.display === "block") {
	            answer.style.display = "none";
	        } else {
	            answer.style.display = "block";
	        }
	    }
	</script>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="container mx-auto py-8">
        <h1 class="text-3xl font-semibold mb-6">Featured Books</h1>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6"></div>
            {% for file in files %}
            <div class="bg-white p-4 rounded-lg shadow-md">
                <img src="{{ file.image.url }}" alt="{{ file.title }}" class="w-full h-48 object-cover mb-4">
                <h2 class="text-xl font-bold mb-2">{{ file.title }}</h2>
                <p class="text-gray-600 mb-2">Author: {{ file.author }}</p>
                <p class="text-gray-700">{{ file.description }}</p>
                <p class="text-gray-800 mt-4">{{ file.price }}</p>
            </div>
            {% endfor %}
    </div>



    {% for category, files in files_by_category.items %}
            {% if files %}
                <div style="grid-column: span 3; text-align: center;">
                    <h1 style="font-size: 24px; font-weight: bold; margin-top: 20px; margin-bottom: 10px;">{{ category.name }}</h1>
                </div>
                <div style="display: flex; flex-wrap: wrap; justify-content: left; gap: 20px;">
                    {% for file in files %}
                        {% if forloop.counter <= 3 %} {# Display only the first 6 files #}
                            <div style="flex: 0 0 calc(33.33% - 20px); margin-bottom: 20px; border: none; border-radius: 5px; text-align: center;">
                                {% if file.image %}
                                    <img src="{{ file.image.url }}" alt="{{ file.title }} Image" style="width: 100%; border-top-left-radius: 5px; border-top-right-radius: 5px;">
                                {% endif %}
                                <div style="padding: 10px;">
                                    <h2 style="font-size: 20px; margin-bottom: 10px; font-family: Arial, sans-serif;"><strong>{{ file.title }}</strong></h2>
                                    <p style="font-size: 16px; margin-bottom: 5px; font-family: Arial, sans-serif;"><strong>Author:</strong> {{ file.author }}</p>
                                    <p style="font-size: 16px; margin-bottom: 5px; font-family: Arial, sans-serif;"><strong>Category:</strong> {{ file.category }}</p>
                                    <p style="font-size: 16px; margin-bottom: 10px; font-family: Arial, sans-serif;"><strong>Price:</strong> {{ file.price }}</p>
                                    <p style="font-size: 16px; margin-bottom: 10px; font-family: Arial, sans-serif;"><strong>Rating:</strong> {{ file.rating }}</p>
                                    <a href="{% url 'file:payment' file_id=file.id %}" style="display: inline-block; padding: 8px 16px; background-color: #FD6C01; color: white; border-radius: 5px; text-decoration: none; font-family: Arial, sans-serif;">Buy Book</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                {% if files|length > 3 %} {# Display "MORE BOOKS" button if there are more than 6 files #}
                    <div style="text-align: center;">
                        <a href="{% url 'file:files' %}" style="font-size: 18px; color: #FD6C01; text-decoration: none; font-weight: bold; font-family: Arial, sans-serif;">MORE BOOKS</a>
                    </div>
                {% endif %}
            {% endif %}
    {% endfor %}      
     
{% endblock %}

books/templates/books/login.html
{% extends 'books/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
	<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
	    <h1 class="mb-6 text-3xl">Log in</h1>

	    <form method="post" action=".">
	        {% csrf_token %}

	        <div class="mb-3">
	            <label class="inline-block mb-2">Username</label><br>
	            {{ form.username }}
	        </div>

	        <div class="mb-3">
	            <label class="inline-block mb-2">Password</label><br>
	            {{ form.password }}
	        </div>

	        {% if form.errors or form.non_field_errors %}
	            <div class="mb-3 p-6 bg-red-100 rounded-xl">
	                {% for field in form %}
	                    {{ field.errors }}
	                {% endfor %}

	                {{ form.non_field_errors }}
	            </div>
	        {% endif %}

	        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
	    </form>
	</div>
{% endblock %}

books/templates/books/logout.html
{% extends 'books/base.html' %}

{% block title %}Logged out{% endblock %}

{% block content %}
    <h1>Logout</h1>
    <p>Are you sure you want to logout?</p>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

books/templates/books/privacy.html
{% extends 'books/base.html' %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
	<div class="container" style="max-width: auto; margin: 0 auto; padding: 20px; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5; color: #333; margin-top: 60px;">
	    <div style="background-color: #219ebc; padding: 1rem; border-radius: 1rem; text-align: center; margin-top: 30px; margin-bottom: 20px;">
		    <h1 style="font-size: 1.5rem; font-weight: bold;">Privacy Policy</h1>
		    <div style="border-bottom: 1px solid #000000; margin: 1rem auto; width: 6.4rem;"></div>
		</div>

	    <p style="margin-bottom: 20px; font-weight: bold;">Effective Date: 14th February 2024</p>

	    <p style="font-size: 24px; font-weight: bold; margin-bottom: 20px;">Welcome to Digi_Library!</p>

	    <p style="margin-bottom: 20px;">At Digi_Library, we value the privacy of our users and are committed to protecting it. This Privacy Policy outlines how we collect, use, disclose, and safeguard your personal information when you use our website.</p>

	    <h2 style="font-size: 24px; font-weight: bold; margin-bottom: 20px;">Information We Collect</h2>

	    <p style="margin-bottom: 20px;">We may collect personal information from you when you register on our site, place an order, subscribe to our newsletter, respond to a survey, fill out a form, or otherwise interact with our website. The types of personal information we may collect include:</p>

	    <ul style="margin-bottom: 20px;">
	        <li>Name</li>
	        <li>Email address</li>
	        <li>Mailing address</li>
	        <li>Phone number</li>
	        <li>Payment information</li>
	        <li>Demographic information</li>
	        <li>Other information relevant to customer surveys and/or offers</li>
	    </ul>

	    <!-- Add more content as needed -->

	    <div style="margin-bottom: 30px;">
		    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 2px;">Data Security</h1>

		    <p>We are committed to ensuring that your information is secure. We have implemented suitable physical, electronic, and managerial procedures to safeguard and secure the information we collect online.</p>
		</div>

		<div style="margin-bottom: 30px;">
		    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 2px;">Sharing Your Information</h1>

		    <p>We do not sell, trade, or otherwise transfer your personal information to third parties without your consent. However, we may share your information with trusted third parties who assist us in operating our website, conducting our business, or servicing you, as long as those parties agree to keep this information confidential.</p>
		</div>

		<div style="margin-bottom: 30px;">
		    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 2px;">Cookies</h1>

		    <p>Our website uses cookies to enhance your browsing experience. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information.</p>
		</div>

		<div style="margin-bottom: 30px;">
		    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 2px;">Changes to This Privacy Policy</h1>

		    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
		</div>


	</div>

{% endblock %}

books/templates/books/signup.html
{% extends 'books/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
	<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
		<h1 class="mb-6 text-3xl">Sign up</h1>

		<form method="post" action=".">
			{% csrf_token %}

			<div class="mb-3">
				<label class="inline-block mb-2">Username</label>
				{{ form.username }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Email</label>
				{{ form.email }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Password</label>
				{{ form.password1 }}
			</div>

			<div class="mb-3">
				<label class="inline-block mb-2">Repeat password</label>
				{{ form.password2 }}
			</div>

			{% if form.errors or form.non_field_errors %}
				<div class="mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %}
						{{ field.errors }}
					{% endfor %}

					{{ form.non_field_errors }}
				</div>
			{% endif %}

			<button class="py-4 px-8 text-lg bg-blue-500 hover:bg-teal-700 rounded-xl text-black">Submit</button>
		</form>
	</div>
{% endblock %}