conversation/urls.py
from django.urls import path

from . import views

# coversation/urls.py
# Set the namespace for the app
app_name = 'conversation'

# Define the urlpatterns for the app
urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:file_pk>/', views.new_conversation, name='new'),
]

file/urls.py
from django.urls import path

from . import views

app_name = 'file'

urlpatterns = [
    path('', views.files, name='files'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:file_id>/download/', views.download, name='download'),  # Corrected URL pattern
    path('<int:file_id>/payment/', views.payment, name='payment'),
    path('<int:file_id>/process_payment/', views.process_payment, name='process_payment'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('books.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('file/', include('file.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    """
    Represents a category for files in the application.
    """
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class File(models.Model):
    """
    Represents a file(book) for sale in the application.
    """
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publication_year = models.PositiveIntegerField()
    category = models.ForeignKey(Category, related_name='files', on_delete=models.CASCADE)
    language = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    available = models.BooleanField(default=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    num_ratings = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='file_images', blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='uploaded_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    file_type = models.CharField(max_length=50, choices=[('pdf', 'PDF'), ('slides', 'Slides'), ('doc', 'Doc')])
    file = models.FileField(upload_to='docs/')

    def __str__(self):
        return self.title


class Payment(models.Model):
    """
    Represents payment for the file/doc(BOOK) to be downloaded
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    paid = models.BooleanField(default=False)

file/forms.py
from django import forms
from .models import File

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewFileForm(forms.ModelForm):
    """
    Form class for creating a new item.

    Inherits from Django's ModelForm class.
    Sets the Meta class to specify the File model and fields to include.
    Defines custom widgets for certain fields.
    """
    class Meta:
        model = File
        fields = ('category', 'title', 'author', 'publication_year', 'language', 'price', 'rating', 'image', 'file_type', 'file')
        widgets = {
            'category': forms.Select(attrs={'class': INPUT_CLASSES}),
            'title': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'author': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'publication_year': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'language': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'price': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'rating': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
            'file_type': forms.Select(attrs={'class': INPUT_CLASSES}),
            'file': forms.FileInput(attrs={'class': INPUT_CLASSES})
        }

class EditFileForm(forms.ModelForm):
    """
    Form class for editing an existing item.

    Inherits from Django's ModelForm class.
    Sets the Meta class to specify the Item model and fields to include.
    Defines custom widgets for certain fields.
    """
    class Meta:
        model = File
        fields = ('author', 'category', 'title', 'price', 'image', 'file', 'available', )
        widgets = {
            'author': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'title': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'category': forms.Select(attrs={'class': INPUT_CLASSES}),
            'price': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'image': forms.FileInput(attrs={'class': INPUT_CLASSES}),
            'file': forms.FileInput(attrs={'class': INPUT_CLASSES}),
            'available': forms.CheckboxInput(attrs={'class': INPUT_CLASSES})
        }

file/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewFileForm, EditFileForm
from .models import Category, File, Payment


def files(request):
    """
    Renders the files page with a list of files based on the request parameters.
    Parameters:
        - request: The HTTP request object.
    Returns:
        - The rendered items.html template with the items, query, categories,
        and category_id context variables.
    """
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    files = File.objects.all()

    if category_id:
        files = files.filter(category_id=category_id)

    if query:
        files = files.filter(Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, 'file/files.html', {
        'files': files,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def detail(request, pk):
    """
     Renders the detail page for a specific item.
    Parameters:
        - request: The HTTP request object.
        - pk: The primary key of the item.
    Returns:
        - The rendered detail.html template with the item and related_items context variables.
    """
    file = get_object_or_404(File, pk=pk)
    related_files = File.objects.filter(category=file.category, available=True).exclude(pk=pk)[0:3]

    return render(request, 'file/detail.html', {
        'file': file,
        'related_files': related_files
    })

@login_required
def new(request):
    """
    Renders the new item form page and handles form submission to create a new item.
    Parameters:
        - request: The HTTP request object.
    Returns:
        - If the request method is POST and the form is valid,
        redirects to the item detail page for the new item.
        - If the request method is not POST, renders the form.html
        template with the new item form and title context variables.
    """
    if request.method == 'POST':
        form = NewFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.created_by = request.user
            file.save()

            return redirect('file:detail', pk=file.id)
    else:
        form = NewFileForm()

    return render(request, 'file/form.html', {
        'form': form,
        'title': 'New file',
    })


@login_required
def edit(request, pk):
    """
     Renders the edit item form page and handles form submission to edit an existing item.
    Parameters:
        - request: The HTTP request object.
        - pk: The primary key of the item.
    Returns:
        - If the request method is POST and the form is valid, redirects to
        the item detail page for the edited item.
        - If the request method is not POST, renders the form.html template with
        the edit item form and title context variables.
    """
    file = get_object_or_404(File, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditFileForm(request.POST, request.FILES, instance=file)

        if form.is_valid():
            form.save()

            return redirect('file:detail', pk=file.id)
    else:
        form = EditFileForm(instance=file)

    return render(request, 'file/form.html', {
        'form': form,
        'title': 'Edit file',
    })

@login_required
def delete(request, pk):
    """
     Deletes an item specified by its primary key and the authenticated user.
    Parameters:
        request (HttpRequest): The HTTP request object.
        pk (int): The primary key of the item to be deleted.
    Returns:
        HttpResponseRedirect: A redirect response to the index page of the dashboard.
    """
    file = get_object_or_404(File, pk=pk, created_by=request.user)
    file.delete()

    return redirect('dashboard:index')


@login_required
def process_payment(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    # Process payment using your payment gateway here
    # Assuming payment is successful
    payment = Payment.objects.create(user=request.user, file=file, paid=True)
    return redirect('file:download', file_id=file_id)  # Corrected redirect URL

@login_required
def download(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    # Check if the user has made a payment for the file
    if not Payment.objects.filter(user=request.user, file=file, paid=True).exists():
        # Redirect the user to the payment page or form
        return redirect('file:payment', file_id=file_id)  # Use correct URL name
    else:
        # User has made a payment, allow file download
        # You can implement file download logic here
        # For example, return a response with the file content
        return render(request, 'file/download.html', {'file': file})

@login_required
def payment(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    # Render the payment page or form
    return render(request, 'file/payment.html', {'file': file})

file/templates/file/detail.html
{% extends 'books/base.html' %}

{% block title %}{{ file.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6" style="margin-top: 65px;">
    <div class="col-span-3">
        <img src="{{ file.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ file.title }}</h1>
        <p class="text-gray-500"><strong>Ksh: </strong>{{ file.price }}</p>
        <p class="text-gray-500"><strong>Freelancer: </strong>{{ file.created_by.username }}</p>
    
        {% if file.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ file.description }}
            </p>
        {% endif %}

        {% if request.user == file.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your book!</p>

                <a href="{% url 'file:edit' file.id %}" style="display: inline-block; margin-top: 6px; padding: 0.75rem 2.5rem; font-size: 1.125rem; font-weight: 600; background-color: teal; color: #ffffff; border-radius: 0.75rem;">Edit</a>

                <a href="{% url 'file:delete' file.id %}" style="display: inline-block; margin-top: 6px; padding: 0.75rem 2.5rem; font-size: 1.125rem; font-weight: 600; background-color: #9e211e; color: #ffffff; border-radius: 0.75rem;">Delete</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' file.id %}" style="display: inline-block; margin-top: 6px; padding: 0.75rem 1.5rem; font-size: 1.125rem; font-weight: 600; background-color: #34d399; color: #ffffff; border-radius: 0.75rem; text-decoration: none; cursor: pointer; transition: background-color 0.25s ease-in-out">Contact seller</a>
        {% endif %}

            
        {% if user_has_paid %}
            <!-- Display the download button -->
            <a href="{{ file.file.url }}" download>Download File</a>
        {% else %}
            <!-- Display a message or button prompting the user to proceed to the payment page -->
            <p>You need to make a payment to access the download button.</p>
        {% endif %}

        <a href="{% url 'file:payment' file.id %}" style="display: inline-block; margin-top: 6px; padding: 0.75rem 1.5rem; font-size: 1.125rem; font-weight: 600; background-color: #45d399; color: #ffffff; border-radius: 0.75rem; text-decoration: none; cursor: pointer; transition: background-color 0.25s ease-in-out">Pay Now</a>

    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Books</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for file in related_files %}
            <div>
                <a href="{% url 'file:detail' file.id %}">
                    <div>
                        <img src="{{ file.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ file.title }}</h2>
                        <p class="text-gray-500">{{ file.categoty }}</p>
                        <p class="text-gray-500">{{ file.rating }}</p>
                        <p class="text-gray-500">{{ file.file_type }}</p>
                        <p class="text-gray-500">{{ file.file }}</p>
                        <p class="text-gray-500">Price: {{ file.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

file/templates/file/download.html
{% extends 'books/base.html' %}

{% block title %}Download{% endblock %}

{% block content %}
	<h1 style="color:#333;">File Details</h1>
    <p style="">Title: {{ file.title }}</p>
    <p style="">Author: {{ file.author }}</p>
    <p style="">Publication Year: {{ file.publication_year }}</p>
    <!-- Add more details about the file as needed -->
    <a href="{{ file.file.url }}" target="_blank" style="align:center; margin-top: 0.5rem; padding: 0.5rem 0.9rem; display: inline-block; background-color: #FD6C01; font-size: 1.5rem; border-radius: 1.5rem; color: white; text-decoration: none;">Download File</a>
{% endblock %}

file/templates/file/files.html
{% extends 'books/base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
    <div style="padding-bottom: 1.5rem; display: grid; grid-template-columns: repeat(4, 1fr); grid-gap: 1rem; background-color: #f3f4f6; font-family: Arial, sans-serif; margin-top: 45px;">
        <div class="col-span-1">
            <form method="get" action="{% url 'file:files' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a business, fiction, self-help book...">

                <button style="margin-top: 1rem; padding: 0.5rem 2rem; font-size: 1.2rem; background-color: #219ebc; color: #ffffff; border-radius: 0.75rem;">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'file:files' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'file:files' %}" style="margin-top: 0.5rem; padding: 1.2rem 2.4rem; display: inline-block; background-color: #FD6C01; font-size: 1.5rem; border-radius: 1.5rem; color: white; text-decoration: none;">Clear</a>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for file in files %}
                    <div>
                        <a href="{% url 'file:detail' file.id %}">
                            <div>
                                <img src="{{ file.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ file.title }}</h2>
                                <p class="font-semibold">{{ file.author }}</p>
                                <p class="font-semibold">{{ file.category }}</p>
                                <p class="text-gray-500">Ksh: {{ file.price }}</p>
                                <a href="{% url 'file:payment' file.id %}" style="margin-top: 0.5rem; padding: 0.5rem 0.9rem; display: inline-block; background-color: #FD6C01; font-size: 1.5rem; border-radius: 1.5rem; color: white; text-decoration: none;">Buy Book</a>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

file/templates/file/form.html
{% extends 'books/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl" style="margin-top: 65px;">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data" style="margin-top: 15px;">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button style="margin-top: 6px; padding: 0.8rem 3rem; font-size: 1.25rem; background-color: teal; color: #ffffff; border-radius: 0.75rem; cursor: pointer; transition: background-color 0.25s ease-in-out;">Submit</button>
    </form>
{% endblock %}

file/templates/file/payment.html
{% extends 'books/base.html' %}

{% block title %}Payment{% endblock %}

{% block content %}
	<h1 style="font-size: 24px; font-weight: bold; margin-bottom: 10px;">Payment Details</h1>

	<p style="font-size: 16px; margin-bottom: 10px;">You are about to purchase the following file:</p>

	<div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
	    
	</div>

	<div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
	    <div style="width: 40%;">
	        <img src="{{ file.image.url }}" alt="{{ file.title }}" style="max-width: 100%; height: auto; border-radius: 10px;">
	    </div>
	    <div style="width: 55%;">
	    	<div style="width: 45%;">
		        <p style="font-size: 25px; margin-bottom: 10px;"><strong style="font-weight: bold; font-size: 30px;">Title:</strong> {{ file.title }}</p>
	    	</div>

	    	<div style="width: 45%;">
		        <p style="font-size: 25px; margin-bottom: 10px;"><strong style="font-weight: bold; font-size: 30px;">Author:</strong> {{ file.author }}</p>
		    </div>

		    <div style="width: 45%;">
		        <p style="font-size: 25px; margin-bottom: 10px;"><strong style="font-weight: bold; font-size: 30px;">Category:</strong> {{ file.category }}</p>
		    </div>

		   	<div style="width: 45%;">
		        <p style="font-size: 25px; margin-bottom: 10px;"><strong style="font-weight: bold; font-size: 30px;">Price:</strong> {{ file.price }}</p>
		    </div>

	        <form action="{% url 'file:process_payment' file_id=file.id %}" method="post" style="display: flex; flex-direction: column; width: 100%;">
	            {% csrf_token %}
	            <label for="card_number" style="font-size: 16px; margin-bottom: 5px;"><strong>Card Number:</strong></label>
	            <input type="text" id="card_number" name="card_number" required style="margin-bottom: 10px;">
	            <label for="expiry_date" style="font-size: 16px; margin-bottom: 5px;">Expiry Date:</label>
	            <input type="text" id="expiry_date" name="expiry_date" required style="margin-bottom: 10px;">
	            <label for="cvv" style="font-size: 16px; margin-bottom: 5px;">CVV:</label>
	            <input type="text" id="cvv" name="cvv" required style="margin-bottom: 10px;">
	            <a href="{% url 'file:process_payment' file_id=file.id %}" style="font-size: 16px; background-color: #219ebc; color: white; padding: 10px 20px; border: none; cursor: pointer;">Make Payment</a>
	        </form>
	    </div>
	</div>
{% endblock %}

file/templates/file/process_payment.html
{% extends 'books/base.html' %}

{% block title %}Payment{% endblock %}

{% block content %}
	<h1>Payment Processing</h1>

    <!-- Display a confirmation message -->
    <p>Thank you for your payment!</p>
    <p>Your payment has been successfully processed.</p>

    <!-- Optionally, provide additional details or instructions -->
    <p>You can now download the file.</p>

    <!-- Add a link to redirect users to the file download page -->
    <a href="{{ file.file.url }}" style="margin-top: 0.5rem; padding: 0.5rem 0.9rem; display: inline-block; background-color: #FD6C01; font-size: 1.5rem; border-radius: 1.5rem; color: white; text-decoration: none;">Download File</a>
{% endblock %}